"""Added Authentication to the users

Revision ID: 78430358fcf4
Revises: 7f1e472758fd
Create Date: 2024-01-29 02:35:07.471915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78430358fcf4'
down_revision = '7f1e472758fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uniq_email', ['email'])  # Name the unique constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uniq_email', type_='unique')  # Drop the named unique constraint
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
